In [3]:
import pandas as pd
data = {
    "Source_IP": [
        "10.0.0.1",
        "10.0.0.2",
        "10.0.0.3",
        "10.0.0.4",
        "10.0.0.5",
        "10.0.0.6",
        "10.0.0.7",
        "10.0.0.8"
    ],

    "Destination_Port": [
        80,
        443,
        22,
        80,
        53,
        443,
        22,
        80
    ],

    "Packets": [
        120,
        500,
        80,
        1000,
        50,
        450,
        70,
        800
    ],

    "Attack": [
        "BENIGN",
        "DDoS",
        "BENIGN",
        "DDoS",
        "BENIGN",
        "DDoS",
        "BENIGN",
        "PortScan"
    ]
}

df = pd.DataFrame(data)

df

  Source_IP  Destination_Port  Packets    Attack
0  10.0.0.1                80      120    BENIGN
1  10.0.0.2               443      500      DDoS
2  10.0.0.3                22       80    BENIGN
3  10.0.0.4                80     1000      DDoS
4  10.0.0.5                53       50    BENIGN
5  10.0.0.6               443      450      DDoS
6  10.0.0.7                22       70    BENIGN
7  10.0.0.8                80      800  PortScan

In [4]:
df.shape

(8, 4)

In [5]:
df.columns

Index(['Source_IP', 'Destination_Port', 'Packets', 'Attack'], dtype='object')

In [6]:
df.head()

  Source_IP  Destination_Port  Packets  Attack
0  10.0.0.1                80      120  BENIGN
1  10.0.0.2               443      500    DDoS
2  10.0.0.3                22       80  BENIGN
3  10.0.0.4                80     1000    DDoS
4  10.0.0.5                53       50  BENIGN

In [8]:
df.tail()

  Source_IP  Destination_Port  Packets    Attack
3  10.0.0.4                80     1000      DDoS
4  10.0.0.5                53       50    BENIGN
5  10.0.0.6               443      450      DDoS
6  10.0.0.7                22       70    BENIGN
7  10.0.0.8                80      800  PortScan

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Source_IP         8 non-null      object
 1   Destination_Port  8 non-null      int64
 2   Packets           8 non-null      int64
 3   Attack            8 non-null      object
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes

In [10]:
df.describe()

       Destination_Port      Packets
count          8.000000     8.000000
mean         152.875000   383.750000
std          180.676852   366.954162
min           22.000000    50.000000
25%           45.250000    77.500000
50%           80.000000   285.000000
75%          170.750000   575.000000
max          443.000000  1000.000000

In [13]:
df["Packets"]

0     120
1     500
2      80
3    1000
4      50
5     450
6      70
7     800
Name: Packets, dtype: int64

In [14]:
df[["Source_IP", "Attack"]]

  Source_IP    Attack
0  10.0.0.1    BENIGN
1  10.0.0.2      DDoS
2  10.0.0.3    BENIGN
3  10.0.0.4      DDoS
4  10.0.0.5    BENIGN
5  10.0.0.6      DDoS
6  10.0.0.7    BENIGN
7  10.0.0.8  PortScan

In [15]:
ddos = df[df["Attack"] == "DDoS"]

ddos

  Source_IP  Destination_Port  Packets Attack
1  10.0.0.2               443      500   DDoS
3  10.0.0.4                80     1000   DDoS
5  10.0.0.6               443      450   DDoS

In [17]:
hightraffic=df[df["Packets"]>500]
hightraffic

  Source_IP  Destination_Port  Packets    Attack
3  10.0.0.4                80     1000      DDoS
7  10.0.0.8                80      800  PortScan

In [20]:
benign=df[df["Attack"]=="BENIGN"]
benign

  Source_IP  Destination_Port  Packets  Attack
0  10.0.0.1                80      120  BENIGN
2  10.0.0.3                22       80  BENIGN
4  10.0.0.5                53       50  BENIGN
6  10.0.0.7                22       70  BENIGN

In [22]:
import numpy as np  
df.loc[2, "Packets"] = np.nan

df

  Source_IP  Destination_Port  Packets    Attack
0  10.0.0.1                80    120.0    BENIGN
1  10.0.0.2               443    500.0      DDoS
2  10.0.0.3                22      NaN    BENIGN
3  10.0.0.4                80   1000.0      DDoS
4  10.0.0.5                53     50.0    BENIGN
5  10.0.0.6               443    450.0      DDoS
6  10.0.0.7                22     70.0    BENIGN
7  10.0.0.8                80    800.0  PortScan

In [23]:
df.isnull()

   Source_IP  Destination_Port  Packets  Attack
0      False             False    False   False
1      False             False    False   False
2      False             False     True   False
3      False             False    False   False
4      False             False    False   False
5      False             False    False   False
6      False             False    False   False
7      False             False    False   False

In [24]:
df.isnull().sum()

Source_IP           0
Destination_Port    0
Packets             1
Attack              0
dtype: int64

In [26]:
df["Packets"] = df["Packets"].fillna(0)

In [27]:
df.head()

  Source_IP  Destination_Port  Packets  Attack
0  10.0.0.1                80    120.0  BENIGN
1  10.0.0.2               443    500.0    DDoS
2  10.0.0.3                22      0.0  BENIGN
3  10.0.0.4                80   1000.0    DDoS
4  10.0.0.5                53     50.0  BENIGN

In [28]:
df.isnull().sum()

Source_IP           0
Destination_Port    0
Packets             0
Attack              0
dtype: int64

In [29]:
df["Attack"].value_counts()

Attack
BENIGN      4
DDoS        3
PortScan    1
Name: count, dtype: int64

In [30]:
df.groupby("Attack")["Packets"].mean()

Attack
BENIGN       60.0
DDoS        650.0
PortScan    800.0
Name: Packets, dtype: float64

In [31]:
df.to_csv("../data/mini_network_traffic.csv", index=False)

In [34]:
print("Dataset shape:", traffic_df.shape)

print("\nColumn names:")
print(traffic_df.columns.tolist())

print("\nAttack distribution:")
print(traffic_df["Attack"].value_counts())

print("\nMissing values:")
print(traffic_df.isnull().sum())

print("\nAverage packets by attack:")
print(
    traffic_df.groupby("Attack")["Packets"].mean()
)

NameError: name 'traffic_df' is not defined